/*
 * JSP generated by Resin-3.0.21 (built Thu, 10 Aug 2006 12:03:19 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.sql.*;

public class _profile__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      uk.ac.dundee.computing.stewarttaylor.ProfileBean profileBean;
      synchronized (session) {
        profileBean = (uk.ac.dundee.computing.stewarttaylor.ProfileBean) session.getAttribute("profileBean");
        if (profileBean == null) {
          profileBean = new uk.ac.dundee.computing.stewarttaylor.ProfileBean();
          session.setAttribute("profileBean", profileBean);
        }
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
      uk.ac.dundee.computing.stewarttaylor.UserBean userBean2;
      synchronized (session) {
        userBean2 = (uk.ac.dundee.computing.stewarttaylor.UserBean) session.getAttribute("userBean2");
        if (userBean2 == null) {
          userBean2 = new uk.ac.dundee.computing.stewarttaylor.UserBean();
          session.setAttribute("userBean2", userBean2);
        }
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
				uk.ac.dundee.computing.stewarttaylor.UserBean uBeanS = (uk.ac.dundee.computing.stewarttaylor.UserBean)session.getAttribute("userBean");
				String sName = uBeanS.getUsername();
				out.print(sName);
			
      out.write(_jsp_string2, 0, _jsp_string2.length);
       
			
			  

			
			
			out.print(sName);    
      out.write(_jsp_string3, 0, _jsp_string3.length);
        out.print(((uk.ac.dundee.computing.stewarttaylor.ProfileBean) pageContext.findAttribute("profileBean")).getUsername());
      out.write(_jsp_string4, 0, _jsp_string4.length);
        out.print(((uk.ac.dundee.computing.stewarttaylor.ProfileBean) pageContext.findAttribute("profileBean")).getImage());
      out.write(_jsp_string5, 0, _jsp_string5.length);
        out.print(((uk.ac.dundee.computing.stewarttaylor.ProfileBean) pageContext.findAttribute("profileBean")).getJoindate());
      out.write(_jsp_string6, 0, _jsp_string6.length);
        out.print(((uk.ac.dundee.computing.stewarttaylor.ProfileBean) pageContext.findAttribute("profileBean")).getMessageCount());
      out.write(_jsp_string7, 0, _jsp_string7.length);
      
	
	if( profileBean.getOwnProfile() == false)
	{
		if( profileBean.getFollowed() == false)
		{
		
		
      out.write(_jsp_string8, 0, _jsp_string8.length);
        out.print(((uk.ac.dundee.computing.stewarttaylor.ProfileBean) pageContext.findAttribute("profileBean")).getUsername());
      out.write(_jsp_string9, 0, _jsp_string9.length);
      
	
		}
		else
		{
		
				
      out.write(_jsp_string10, 0, _jsp_string10.length);
        out.print(((uk.ac.dundee.computing.stewarttaylor.ProfileBean) pageContext.findAttribute("profileBean")).getUsername());
      out.write(_jsp_string11, 0, _jsp_string11.length);
      
		
		
		
		}
		
	}
	
	
	
	

	
      out.write(_jsp_string12, 0, _jsp_string12.length);
      

	try 
	{

		String[] follows = profileBean.getFollows();

	 

	 for(int i = 0 ; i< follows.length ; i++)
	 {
	 
	 
		 
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(follows[i]); 
      out.write(_jsp_string14, 0, _jsp_string14.length);
       out.println(follows[i]); 
      out.write(_jsp_string15, 0, _jsp_string15.length);
       
	 
	 }
	 }
	 catch(Exception E)
	 {
		//out.println("<h3> No Posts Retrieved</h3>");
	}
	

      out.write(_jsp_string16, 0, _jsp_string16.length);
      

	try 
	{

		String[] followers = profileBean.getFollowers();

	 

	 for(int i = 0 ; i< followers.length ; i++)
	 {
	 
	 
		 
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(followers[i]); 
      out.write(_jsp_string14, 0, _jsp_string14.length);
       out.println(followers[i]); 
      out.write(_jsp_string15, 0, _jsp_string15.length);
       
	 
	 }
	 }
	 catch(Exception E)
	 {
		//out.println("<h3> No Posts Retrieved</h3>");
	}
	

      out.write(_jsp_string17, 0, _jsp_string17.length);
      
	
	

	
	if(profileBean.getOwnProfile() == true)
	{
	
	
	
      out.write(_jsp_string18, 0, _jsp_string18.length);
      
		}
						

      out.write(_jsp_string19, 0, _jsp_string19.length);
      uk.ac.dundee.computing.stewarttaylor.MessageBean msgBean;
      synchronized (session) {
        msgBean = (uk.ac.dundee.computing.stewarttaylor.MessageBean) session.getAttribute("msgBean");
        if (msgBean == null) {
          msgBean = new uk.ac.dundee.computing.stewarttaylor.MessageBean();
          session.setAttribute("msgBean", msgBean);
        }
      }
      out.write(_jsp_string20, 0, _jsp_string20.length);
      

try 
{

	String[] names = msgBean.getUsername();
	String[] dates = msgBean.getDate();
	String[] messages = msgBean.getMessage();
	String[] images = msgBean.getImage();
	boolean[] canDelete = msgBean.getCanDelete();
	int[] id = msgBean.getID();
 
 
 
 for(int i = 0 ; i< names.length ; i++)
 {
 
 
 
 
 
	 
      out.write(_jsp_string21, 0, _jsp_string21.length);
       out.println(names[i]); 
      out.write(_jsp_string22, 0, _jsp_string22.length);
       out.println(names[i]); 
      out.write(_jsp_string23, 0, _jsp_string23.length);
       out.println(dates[i]); 
      out.write(_jsp_string24, 0, _jsp_string24.length);
      
		   
			   
				if (canDelete[i] == true)
				{
			   
			   
      out.write(_jsp_string25, 0, _jsp_string25.length);
       out.println(id[i]); 
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
			   
			 
				}
		   
		   
		   
		   
		   
      out.write(_jsp_string27, 0, _jsp_string27.length);
       out.println(images[i]); 
      out.write(_jsp_string28, 0, _jsp_string28.length);
       out.println(messages[i]); 
      out.write(_jsp_string29, 0, _jsp_string29.length);
       
 
 }
 }
 catch(Exception E)
 {
    out.println("<h3> No Posts Retrieved</h3>");
	
}

      out.write(_jsp_string30, 0, _jsp_string30.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -6418134904411496499L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("profile.jsp"), 3910580962130683300L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("parts/header.jsp"), 4882967369600160189L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("parts/messageBox.jsp"), 4695996236894547340L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("parts/messagesDisplay.jsp"), 4054012001612230713L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string24;
  private final static char []_jsp_string28;
  private final static char []_jsp_string2;
  private final static char []_jsp_string4;
  private final static char []_jsp_string12;
  private final static char []_jsp_string15;
  private final static char []_jsp_string22;
  private final static char []_jsp_string30;
  private final static char []_jsp_string6;
  private final static char []_jsp_string20;
  private final static char []_jsp_string23;
  private final static char []_jsp_string29;
  private final static char []_jsp_string8;
  private final static char []_jsp_string11;
  private final static char []_jsp_string18;
  private final static char []_jsp_string14;
  private final static char []_jsp_string19;
  private final static char []_jsp_string0;
  private final static char []_jsp_string10;
  private final static char []_jsp_string21;
  private final static char []_jsp_string13;
  private final static char []_jsp_string27;
  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  private final static char []_jsp_string16;
  private final static char []_jsp_string26;
  private final static char []_jsp_string9;
  private final static char []_jsp_string17;
  private final static char []_jsp_string5;
  private final static char []_jsp_string7;
  private final static char []_jsp_string25;
  static {
    _jsp_string24 = "</p>\r\n		   \r\n		   \r\n		   ".toCharArray();
    _jsp_string28 = "\" alt=\"Avatar\" />\r\n		   </div>\r\n		   \r\n		   \r\n		   <div id=\"msgText\">\r\n		   <p><xmp>".toCharArray();
    _jsp_string2 = "\r\n			\r\n			\"> \r\n			\r\n			".toCharArray();
    _jsp_string4 = " </h2>\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	<img class=\"avtbig\" src=\"".toCharArray();
    _jsp_string12 = "\r\n	\r\n					<div id=\"profileFriendsBox\" >\r\n	\r\n	\r\n	\r\n	\r\n\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	<h3> Follows</h3>\r\n	\r\n".toCharArray();
    _jsp_string15 = "</a>\r\n			</div>\r\n		   \r\n			".toCharArray();
    _jsp_string22 = "\"> ".toCharArray();
    _jsp_string30 = " \r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n\r\n		   \r\n		   \r\n		   \r\n	\r\n	</div>\r\n     \r\n     \r\n        \r\n  \r\n    \r\n        \r\n        </div><!--end of middle content-->\r\n\r\n\r\n\r\n    \r\n            \r\n      \r\n\r\n\r\n    \r\n	 <div style=\"clear: both;\">\r\n	</div><!-- #content-->\r\n\r\n\r\n\r\n	<footer id=\"footer\">\r\n\r\n		<p>Created By Stewart Taylor</p>\r\n\r\n	</footer><!-- #footer -->\r\n\r\n\r\n\r\n</div><!-- #wrapper -->\r\n\r\n\r\n\r\n</body>\r\n\r\n</html>".toCharArray();
    _jsp_string6 = " </p>\r\n	\r\n	</div>\r\n	\r\n	\r\n		<div id=\"profileStats\" >\r\n	<p>Blabs: ".toCharArray();
    _jsp_string20 = "\r\n	\r\n	\r\n	   ".toCharArray();
    _jsp_string23 = "</a>\r\n		   </div>\r\n		  \r\n		  <div id=\"msgTime\">\r\n		   <p>".toCharArray();
    _jsp_string29 = "</xmp>\r\n		   </p>\r\n		   </div>\r\n		 \r\n		   \r\n	   </div>\r\n	   \r\n	 \r\n	 \r\n	 \r\n	 \r\n 		".toCharArray();
    _jsp_string8 = "\r\n			<form name=\"login\" action=\"/stewarttaylor/follow/".toCharArray();
    _jsp_string11 = "\" >\r\n	<input type=\"submit\"   class=\"btn2\" value=\"UnFollow\" />\r\n	</form>\r\n	".toCharArray();
    _jsp_string18 = "\r\n	\r\n	<h2><a href=\"/stewarttaylor/editprofile/\">Edit Profile</a></h2>\r\n	\r\n	\r\n	\r\n		   	\r\n	<script language = \"Javascript\">\r\nmaxL=140;\r\nvar bName = navigator.appName;\r\nfunction taLimit(taObj) {\r\n	if (taObj.value.length==maxL) return false;\r\n	return true;\r\n}\r\n\r\nfunction taCount(taObj,Cnt) { \r\n	objCnt=createObject(Cnt);\r\n	objVal=taObj.value;\r\n	if (objVal.length>maxL) objVal=objVal.substring(0,maxL);\r\n	if (objCnt) {\r\n		if(bName == \"Netscape\"){	\r\n			objCnt.textContent=maxL-objVal.length;}\r\n		else{objCnt.innerText=maxL-objVal.length;}\r\n	}\r\n	return true;\r\n}\r\nfunction createObject(objId) {\r\n	if (document.getElementById) return document.getElementById(objId);\r\n	else if (document.layers) return eval(\"document.\" + objId);\r\n	else if (document.all) return eval(\"document.all.\" + objId);\r\n	else return eval(\"document.\" + objId);\r\n}\r\n</script>\r\n	\r\n	\r\n	\r\n	\r\n	<div id=\"createMessageBox\">\r\n	 \r\n	\r\n	\r\n	\r\n	<div id=\"messageWriteBox\">\r\n	 <h2>What's on your mind?</h2>\r\n	<form name=\"login\" action=\"/stewarttaylor/post\" >\r\n	\r\n	<textarea onKeyPress=\"return taLimit(this)\" onKeyUp=\"return taCount(this,'myCounter')\" name=\"msg\" class =\"tb4\" cols=\"30\" rows=\"5\"></textarea>\r\n	<p><SPAN id=myCounter>140</SPAN></B> characters remaining</p>\r\n	<input type=\"submit\"   class=\"btn2\" value=\"Post\" />\r\n	</form>\r\n	\r\n	</div>\r\n	\r\n	</div>\r\n\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n\r\n		\r\n		".toCharArray();
    _jsp_string14 = "\">".toCharArray();
    _jsp_string19 = "	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	 <div id=\"mainnewsbox\">\r\n	        <h2>Recent Posts</h2>\r\n       \r\n		    	\r\n		".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE html>\r\n\r\n\r\n\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<head>\r\n\r\n	<meta charset=\"utf-8\" />\r\n\r\n	<!--[if IE]><script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script><![endif]-->\r\n\r\n	<title> </title>\r\n\r\n	<meta name=\"keywords\" content=\"\" />\r\n\r\n	<meta name=\"description\" content=\"\" />\r\n\r\n	<link rel=\"stylesheet\" href=\"/stewarttaylor/style.css\" type=\"text/css\" media=\"screen, projection\" />\r\n\r\n</head>\r\n\r\n\r\n\r\n<body>\r\n\r\n\r\n\r\n\r\n\r\n\r\n<div id=\"wrapper\">\r\n	\r\n	\r\n	\r\n	\r\n\r\n		\r\n		\r\n			\r\n	".toCharArray();
    _jsp_string10 = "\r\n			<form name=\"login\" action=\"/stewarttaylor/unfollow/".toCharArray();
    _jsp_string21 = "\r\n	 \r\n	\r\n	 <div id=\"msgbox\">\r\n	   \r\n		   <div id=\"msgUser\">\r\n		   <a href=\"/stewarttaylor/profile/".toCharArray();
    _jsp_string13 = " \r\n			<div id=\"profileFriend\">\r\n				<a href=\"/stewarttaylor/profile/".toCharArray();
    _jsp_string27 = "\r\n		   \r\n		   \r\n		  <!-- <a href=\"deletemessage/12\">Delete </a> -->\r\n		   </div>\r\n		   \r\n			<div id=\"msgImage\">\r\n				<img src=\"".toCharArray();
    _jsp_string3 = " </a> \r\n\r\n			<a href=\"/stewarttaylor/newsfeed\">Home </a> \r\n\r\n			<a href=\"/stewarttaylor/Logout\">Logout </a> \r\n\r\n			</div>\r\n\r\n		</div>\r\n\r\n\r\n		</div>\r\n\r\n\r\n\r\n		\r\n		\r\n		\r\n		\r\n		\r\n\r\n \r\n    \r\n    \r\n	\r\n  \r\n    \r\n    <div id=\"content\">\r\n    \r\n	\r\n\r\n	<div id=\"profileContent\">\r\n	\r\n	\r\n	\r\n	<div id=\"profileBox\" >\r\n	\r\n	\r\n	\r\n\r\n	\r\n	\r\n	<h2> 	".toCharArray();
    _jsp_string1 = "\r\n\r\n	<div id=\"header\">\r\n    	\r\n		<div id = \"logobox\">\r\n			<img src=\"/stewarttaylor/Images/Logo.png\" alt=\"Logo\" />\r\n		</div>\r\n		\r\n		\r\n		\r\n		\r\n		<div id = \"searchbar\">\r\n				<form name=\"search\" action=\"/stewarttaylor/search/\" method=\"get\" >\r\n					 <input type=\"text\" name=\"search\" />\r\n					<input type=\"submit\"   class=\"btn2\" value=\"Search\" />\r\n				</form>\r\n		</div>\r\n		\r\n		\r\n		\r\n		\r\n				<div id = \"Profilebox\">\r\n\r\n	\r\n		<div class=\"hbuttons\">\r\n			<a href=\"/stewarttaylor/profile/\r\n			\r\n			".toCharArray();
    _jsp_string16 = " \r\n\r\n\r\n		</div>\r\n		\r\n		\r\n		\r\n		\r\n		\r\n		\r\n							<div id=\"profileFriendsBox\" >\r\n	\r\n	<h3> Followers</h3>\r\n	\r\n	".toCharArray();
    _jsp_string26 = "\">Delete </a>\r\n			   \r\n			   ".toCharArray();
    _jsp_string9 = "\" >\r\n	<input type=\"submit\"   class=\"btn2\" value=\"Follow\" />\r\n	</form>\r\n	".toCharArray();
    _jsp_string17 = " \r\n	\r\n\r\n		</div>\r\n	\r\n	\r\n	\r\n	\r\n\r\n	\r\n	\r\n	\r\n\r\n	\r\n	</div>\r\n	\r\n	<div id=\"right_content\">\r\n	\r\n\r\n\r\n	".toCharArray();
    _jsp_string5 = "\" alt=\"avatar\" />\r\n	\r\n\r\n	\r\n	\r\n	<p>Joined <br/>".toCharArray();
    _jsp_string7 = " </p>\r\n	\r\n					\r\n\r\n	\r\n	</div>\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	".toCharArray();
    _jsp_string25 = "\r\n					<a href=\"/stewarttaylor/deletemessage/".toCharArray();
  }
}
